##
## DOES NOT WORK, GIVES CIRCULAR DEPENDENCIES...
##
#  links:
#    - discovery2
#  command: java -jar -Dspring.profiles.active=docker1 microservices/support/discovery-server/build/libs/discovery-server-0.0.1-SNAPSHOT.jar
#  
#discovery2:
#  image: magnus-larsson/spring-boot
#  restart: always
#  ports:
#    - "8762:8762"
#  volumes:
#    - $PWD:/data
#  links:
#    - discovery
#  command: java -jar -Dspring.profiles.active=docker2 microservices/support/discovery-server/build/libs/discovery-server-0.0.1-SNAPSHOT.jar
mysql:
  image: bethke/mysql
  restart: always
  ports:
    - "52022:22"
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=adesso
    - MYSQL_PASSWORD=adesso
    - MYSQL_USER=adesso

rabbitmq:
  image: rabbitmq:3-management
  restart: always
  ports:
    - "5672:5672"
    - "15672:15672"

discovery:
  image: callista/discovery-server
  restart: always
  ports:
    - "8761:8761"

auth:
  image: callista/auth-server
  restart: always
  ports:
    - "9999:9999"
  
turbine:
  image: callista/turbine
  restart: always
  ports:
    - "8989:8989"
  links:
    - rabbitmq
    - monitor
  
product:
  image: callista/product-service
  restart: always
  volumes:
    - $PWD/logs:/logs
  links:
    - discovery

batch:
  image: tot/batch-service
  restart: always
  volumes:
    - $PWD/logs:/logs
  links:
    - discovery
    - mysql

rec:
  image: callista/recommendation-service
  restart: always
  volumes:
    - $PWD/logs:/logs
  links:
    - discovery

rev:
  image: callista/review-service
  restart: always
  volumes:
    - $PWD/logs:/logs
  links:
    - discovery

composite:
  image: callista/product-composite-service
  restart: always
  volumes:
    - $PWD/logs:/logs
  links:
    - discovery
    - rabbitmq

product-api:
  image: callista/product-api-service
  restart: always
  volumes:
    - $PWD/logs:/logs
  links:
    - auth
    - discovery
    - rabbitmq

batch-api:
  image: tot/batch-api-service
  restart: always
  volumes:
    - $PWD/logs:/logs
  links:
    - auth
    - discovery
    - rabbitmq
    - mysql

monitor:
  image: callista/monitor-dashboard
  restart: always
  ports:
    - "7979:7979"
  links:
    - product-api
    - batch-api
    - composite

edge:
  image: callista/edge-server
  restart: always
  ports:
    - "443:8765"
  links:
    - discovery
    - product-api
    - batch-api
